title: DBResolver | Gorm v1
description: Resolve between read and write databases for gorm v1
markdown: kramdown
highlighter: rouge
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-relative-links
  - jekyll-google_search_console_verification_file

kramdown:
  syntax_highlighter: rouge

relative_links:
  enabled: true
  collections: true

google_search_console:
  verification_file_code: 6b05009903c1130d

include:
  - README.md
